name = "play-jonny-casino-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=play-jonny-casino.com.es"
HMAC_KEY = "120f9429ab23b801cc109f54e40b45f360ffd6f925bc49598940a8438eacd77b"
COOKIE_NAME = "zh7"
PLAY_PATH = "launch"
BUTTON_ID = "pac9a2e272c439df61bdc606bb863d406"
GATE_SALT = "3d984e2a4a119389"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "vsyk"
CTA_SELECTOR = ".play-button"
